# Setup
title: "영원"
tagline: "웹 개발과 일상"
description: "Developer with Cat"
url: https://tocktock.github.io
baseurl: ""
paginate: 5

# About/contact
author:
  name: Park Ji Young
  url: https://tocktock.github.io
  email: qnfmtm666@naver.com
#github
github:
  repo: "https://github.com/Tocktock/tocktock.github.io"

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

# for categories and tags
permalink: /:categories/:title/
